List templates = [
  [
    'assets/images/Basant-Panchami.jpg',
    'assets/vasant panchami/vasant pamchami 1.jpg',
    'assets/vasant panchami/vasant panchami 2.jpg',
    'assets/vasant panchami/vasant panchami 3.jpg',
    'assets/vasant panchami/vasant panchami 4.jpg',
    'assets/vasant panchami/vasant panchami 5.jpg',
    'assets/vasant panchami/vasant panchami 6.jpg',
    'assets/vasant panchami/vasant panchami 7.jpg',
    'assets/vasant panchami/vasant panchami 8.jpg',
    'assets/vasant panchami/vasant panchami 9.jpg',
  ],
  [
    'assets/images/chritmas.jpg',
    'assets/christmas/christmas 1.png',
    'assets/christmas/christmas 2.png',
    'assets/christmas/christmas 3.png',
    'assets/christmas/christmas 4.jpg',
    'assets/christmas/christmas 5.jpg',
    'assets/christmas/christmas 6.jpg',
    'assets/christmas/christmas 7.jpg',
  ],
  [
    'assets/images/diwali.jpg',
    'assets/diwali/diwali.png',
    'assets/diwali/diwali 2.png',
    'assets/diwali/diwali 3.jpg',
    'assets/diwali/diwali 4.png',
    'assets/diwali/diwali 5.png',
    'assets/diwali/diwali 6.png',
    'assets/diwali/diwali 7.png',
    'assets/diwali/diwali 8.png',
    'assets/diwali/diwali 9.jpg',
  ],
  [
    'assets/images/durgaPuja.png',
    'assets/durga puja/durga 1.png',
    'assets/durga puja/durga 2.png',
    'assets/durga puja/durga 3.png',
    'assets/durga puja/durga 4.jpg',
    'assets/durga puja/durga 5.jpg',
    'assets/durga puja/durga 6.jpg',
    'assets/durga puja/durga 7.jpg',
  ],
  [
    'assets/images/dusserha.jpg',
    'assets/dussehra/dussehra 1.jpg',
    'assets/dussehra/dussehra 2.jpg',
    'assets/dussehra/dussehra 3.jpg',
    'assets/dussehra/dussehra 4.jpg',
    'assets/dussehra/dussehra 5.jpg',
    'assets/dussehra/dussehra 6.jpg',
    'assets/dussehra/dussehra 7.jpg',
    'assets/dussehra/dussehra 8.jpg',
  ],
  [
    'assets/images/ganesh.jpg',
    'assets/ganesh/ganesh 1.jpg',
    'assets/ganesh/ganesh 2.jpg',
    'assets/ganesh/ganesh 3.jpg',
    'assets/ganesh/ganesh 4.jpg',
    'assets/ganesh/ganesh 5.jpg',
    'assets/ganesh/ganesh 6.jpg',
    'assets/ganesh/ganesh 7.jpg',
  ],
  [
    'assets/images/gurunanak.jpg',
    'assets/gurunanak/guru 1.jpg',
    'assets/gurunanak/guru 2.jpg',
    'assets/gurunanak/guru 3.jpg',
    'assets/gurunanak/guru 4.jpg',
    'assets/gurunanak/guru 5.jpg',
    'assets/gurunanak/guru 6.jpg',
  ],
  [
    'assets/images/holi.jpg',
    'assets/holi/holi 1.jpg',
    'assets/holi/holi 2.jpg',
    'assets/holi/holi 3.jpg',
    'assets/holi/holi 4.jpg',
    'assets/holi/holi 5.jpg',
    'assets/holi/holi 6.jpg',
    'assets/holi/holi 7.jpg',
  ],
  [
    'assets/images/independence.jpg',
    'assets/independence/independence 1.jpg',
    'assets/independence/independence 2.jpg',
    'assets/independence/independence 3.jpg',
    'assets/independence/independence 4.jpg',
  ],
  [
    'assets/images/janmashtami.jpg',
    'assets/janmashtami/jan 1.jpg',
    'assets/janmashtami/jan 2.jpg',
    'assets/janmashtami/jan 3.jpg',
  ],
  [
    'assets/images/mahashivratri.jpg',
    'assets/mahashivratri/maha 1.jpg',
    'assets/mahashivratri/maha 2.jpg',
    'assets/mahashivratri/maha 3.jpg',
  ],
  [
    'assets/images/navratri.jpg',
    'assets/navratri/navratri 1.jpg',
    'assets/navratri/navratri 2.jpg',
    'assets/navratri/navratri 3.jpg',
  ],
  [
    'assets/images/onam.jpg',
    'assets/onam/onam 1.jpg',
    'assets/onam/onam 2.jpg',
    'assets/onam/onam 3.jpg',
  ],
  [
    'assets/images/rakshabandhan.jpg',
    'assets/rakshabandhan/raksha 1.jpg',
    'assets/rakshabandhan/raksha 2.jpg',
    'assets/rakshabandhan/raksha 3.jpg',
  ],
  [
    'assets/images/rath yatra.jpg',
    'assets/rathyatra/rath 1.jpg',
    'assets/rathyatra/rath 2.jpg',
    'assets/rathyatra/rath 3.jpg',
  ]
];
